import io.github.vlsi.kae.gradle.KotlinArgumentExpressionExtension
import io.github.vlsi.kae.gradle.KotlinArgumentExpressionGradleSubplugin

extensions.create<KotlinArgumentExpressionExtension>(KotlinArgumentExpressionExtension.NAME)

apply<KotlinArgumentExpressionGradleSubplugin>()
